spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9892, localhost:9893, localhost:9894
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9892, localhost:9893, localhost:9894